version: 2

mkdocs:
  configuration: mkdocs.yml

python:
   version: 3.7
   install:
     - requirements: docs/requirements.txt
     - method: pip
         path: .
         extra_requirements:
           - method: setuptools
             path: package