site_name: pyskroutz
site_description: pyskroutz documentation page
site_author: Panagiotis Simakis

theme:
  name: "material"
  palette:
    primary: orange

  features:
    - navigation.instant

repo_url: https://github.com/sp1thas/pyskroutz/

plugins:
- search
- mkdocstrings:
    watch:
      - src/pyskroutz

markdown_extensions:
  - admonition

nav:
  - API:
      - client: 'api/client.md'
      - endpoints: 'api/endpoints.md'
      - models: 'api/models.md'
  - 'Developer Documentation':
      - Contributing: 'contributing.md'
      - Testing: ''
  - About:
      - License: 'license.md'
