site_name: pyskroutz
site_description: pyskroutz documentation page
site_author: Panagiotis Simakis

theme:
  name: "material"
  palette:
    primary: orange

  features:
    - navigation.instant

repo_url: https://github.com/sp1thas/pyskroutz/

plugins:
- search
- mkdocstrings:
    watch:
      - src/pyskroutz

markdown_extensions:
  - admonition
  - pymdownx.keys

nav:
  - API:
      - client: 'api/client.md'
      - Endpoints:
          - books: 'api/endpoints/books.md'
          - categories: 'api/endpoints/categories.md'
          - products: 'api/endpoints/products.md'
          - skus: 'api/endpoints/skus.md'
      - models: 'api/models.md'
  - 'Developer Documentation':
      - Contributing: 'contributing.md'
  - About:
      - License: 'license.md'
