site_name: pyskroutz
site_description: pyskroutz documentation page
site_author: Panagiotis Simakis

theme:
  name: "material"
  palette:
    primary: orange

  features:
    - navigation.sections

repo_url: https://github.com/sp1thas/pyskroutz/

plugins:
- search
- mkdocstrings:
    watch:
      - src/pyskroutz

markdown_extensions:
  - admonition
  - pymdownx.keys

nav:
  - Home: 'index.md'
  - API:
    - Client: 'api/client.md'
    - Resources:
      - Category:
        - Actions: 'api/resources/categories.md'
        - Responses: 'api/models/categories.md'
      - SKU:
        - Actions: 'api/resources/skus.md'
        - Responses: 'api/models/skus.md'
      - Book:
        - Actions: 'api/resources/books.md'
        - Responses: 'api/models/books.md'
      - Product:
        - Actions: 'api/resources/products.md'
        - Responses: 'api/models/products.md'
      - Shop: 'api/resources/shops.md'
      - Manufacturer:
        - Actions: 'api/resources/manufacturers.md'
        - Responses: 'api/models/manufacturers.md'
      - Search: 'api/resources/search.md'
      - Flag: 'api/resources/flags.md'
      - Filter Groups: 'api/resources/filter_groups.md'
      - User Profile: 'api/resources/user_profile.md'
      - User Favorite: 'api/resources/user_favorites.md'
      - User Notifications: 'api/resources/user_notifications.md'
    - Utilities: 'api/utils.md'

  - 'Developer Documentation':
      - Contributing: 'contributing.md'
  - About:
      - License: 'license.md'
