site_name: Welcome to pyskroutz Documentation
site_description: This the pyskroutz documentation page
site_author: Panagiotis Simakis
site_url: https://pyskroutz.simakis.me

theme:
  name: "material"
  palette:
    primary: orange
  custom_dir: "docs/overrides"

  features:
    - navigation.sections

repo_url: https://github.com/sp1thas/pyskroutz/

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/pyskroutz

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: "index.md"
  - API:
      - Client: "api/client.md"
      - Resources:
          - Categories: "api/resources/categories.md"
          - SKUs: "api/resources/skus.md"
          - Books: "api/resources/books.md"
          - Products: "api/resources/products.md"
          - Shops: "api/resources/shops.md"
          - Manufacturers: "api/resources/manufacturers.md"
          - Search: "api/resources/search.md"
          - Flags: "api/resources/flags.md"
          - Filter Groups: "api/resources/filter_groups.md"
          - User Profile: "api/resources/user_profile.md"
          - User Favorite: "api/resources/user_favorites.md"
          - User Notifications: "api/resources/user_notifications.md"
      - Utilities: "api/utils.md"

  - "Developer Documentation":
      - Contributing: "contributing.md"
  - About:
      - License: "license.md"
